npx -p dtsgenerator dtsgen src/application/schema.json -o src/application/schema.d.ts
npx -p dtsgenerator dtsgen src/class/schema.json -o src/class/schema.d.ts
npx -p dtsgenerator dtsgen src/component/schema.json -o src/component/schema.d.ts
npx -p dtsgenerator dtsgen src/directive/schema.json -o src/directive/schema.d.ts
npx -p dtsgenerator dtsgen src/enum/schema.json -o src/enum/schema.d.ts
npx -p dtsgenerator dtsgen src/guard/schema.json -o src/guard/schema.d.ts
npx -p dtsgenerator dtsgen src/interceptor/schema.json -o src/interceptor/schema.d.ts
npx -p dtsgenerator dtsgen src/interface/schema.json -o src/interface/schema.d.ts
npx -p dtsgenerator dtsgen src/module/schema.json -o src/module/schema.d.ts
npx -p dtsgenerator dtsgen src/ng-new/schema.json -o src/ng-new/schema.d.ts
npx -p dtsgenerator dtsgen src/pipe/schema.json -o src/pipe/schema.d.ts
npx -p dtsgenerator dtsgen src/resolver/schema.json -o src/resolver/schema.d.ts
npx -p dtsgenerator dtsgen src/service/schema.json -o src/service/schema.d.ts
npx -p dtsgenerator dtsgen src/service-worker/schema.json -o src/service-worker/schema.d.ts
npx -p dtsgenerator dtsgen src/workspace/schema.json -o src/workspace/schema.d.ts